import { cultivationRealms } from "@/lib/cultivation";

export const frameGroups = [
  "Cảnh giới",
  "Nguyên tố",
  "Linh thú",
  "Đạo hạnh",
  "Đặc biệt",
] as const;
export type AvatarFrame = {
  id: string;
  name: string;
  group: (typeof frameGroups)[number];
  minXp: number;
  color: string;
  symbol: string;
  shape: "ring" | "rays" | "wings" | "jewel" | "runes";
};
export const avatarFrames: AvatarFrame[] = [
  {
    id: "none",
    name: "Không viền",
    group: "Cảnh giới",
    minXp: 0,
    color: "transparent",
    symbol: "",
    shape: "ring",
  },
  ...cultivationRealms.map((realm, index): AvatarFrame => ({
    id: `realm-${index}`,
    name: realm.name,
    group: "Cảnh giới",
    minXp: realm.start,
    color: [
      "#9aa8b6",
      "#7cc9ac",
      "#75d6df",
      "#d2c278",
      "#a6a0ff",
      "#bc8ee7",
      "#6f9be4",
      "#e19cbd",
      "#e4b980",
      "#a3beff",
      "#e0b16f",
      "#ef986a",
      "#a5e5f1",
      "#f0d894",
      "#ffd76a",
    ][index],
    symbol: [
      "○",
      "气",
      "◇",
      "丹",
      "✧",
      "神",
      "虚",
      "合",
      "✶",
      "ϟ",
      "劫",
      "☀",
      "升",
      "仙",
      "帝",
    ][index],
    shape: index < 4 ? "ring" : index < 9 ? "jewel" : "runes",
  })),
  {
    id: "fire",
    name: "Hỏa linh",
    group: "Nguyên tố",
    minXp: 40,
    color: "#ff8a56",
    symbol: "火",
    shape: "rays",
  },
  {
    id: "ice",
    name: "Băng phách",
    group: "Nguyên tố",
    minXp: 40,
    color: "#96e8ff",
    symbol: "❄",
    shape: "jewel",
  },
  {
    id: "thunder",
    name: "Lôi đình",
    group: "Nguyên tố",
    minXp: 80,
    color: "#be9eff",
    symbol: "ϟ",
    shape: "rays",
  },
  {
    id: "wind",
    name: "Phong linh",
    group: "Nguyên tố",
    minXp: 80,
    color: "#a6e3bf",
    symbol: "彡",
    shape: "ring",
  },
  {
    id: "water",
    name: "Thủy nguyệt",
    group: "Nguyên tố",
    minXp: 40,
    color: "#83b7ff",
    symbol: "水",
    shape: "ring",
  },
  {
    id: "shadow",
    name: "Ma ảnh",
    group: "Nguyên tố",
    minXp: 200,
    color: "#d785bc",
    symbol: "魔",
    shape: "rays",
  },
  {
    id: "light",
    name: "Tiên quang",
    group: "Nguyên tố",
    minXp: 200,
    color: "#ffe7a2",
    symbol: "✦",
    shape: "rays",
  },
  {
    id: "dragon",
    name: "Thanh Long",
    group: "Linh thú",
    minXp: 380,
    color: "#62d9ba",
    symbol: "龍",
    shape: "wings",
  },
  {
    id: "phoenix",
    name: "Chu Tước",
    group: "Linh thú",
    minXp: 380,
    color: "#ff9d79",
    symbol: "雀",
    shape: "wings",
  },
  {
    id: "tiger",
    name: "Bạch Hổ",
    group: "Linh thú",
    minXp: 200,
    color: "#e5dfcf",
    symbol: "虎",
    shape: "rays",
  },
  {
    id: "turtle",
    name: "Huyền Vũ",
    group: "Linh thú",
    minXp: 200,
    color: "#7cb4cc",
    symbol: "玄",
    shape: "jewel",
  },
  {
    id: "fox",
    name: "Hồ Ly",
    group: "Linh thú",
    minXp: 80,
    color: "#f2a4d0",
    symbol: "狐",
    shape: "wings",
  },
  {
    id: "qilin",
    name: "Kỳ Lân",
    group: "Linh thú",
    minXp: 640,
    color: "#e2c471",
    symbol: "麟",
    shape: "wings",
  },
  {
    id: "beginner",
    name: "Nhập môn",
    group: "Đạo hạnh",
    minXp: 10,
    color: "#b0d8c1",
    symbol: "Ⅰ",
    shape: "jewel",
  },
  {
    id: "companion",
    name: "Đồng hành",
    group: "Đạo hạnh",
    minXp: 200,
    color: "#9bb9ed",
    symbol: "Ⅱ",
    shape: "jewel",
  },
  {
    id: "devoted",
    name: "Đạo hữu bền bỉ",
    group: "Đạo hạnh",
    minXp: 980,
    color: "#c8a0e8",
    symbol: "Ⅲ",
    shape: "jewel",
  },
  {
    id: "journey",
    name: "Tiên lộ dài lâu",
    group: "Đạo hạnh",
    minXp: 2700,
    color: "#e3c781",
    symbol: "Ⅳ",
    shape: "jewel",
  },
  {
    id: "lotus",
    name: "Liên hoa",
    group: "Đặc biệt",
    minXp: 80,
    color: "#f6bad8",
    symbol: "❀",
    shape: "wings",
  },
  {
    id: "swords",
    name: "Kiếm trận",
    group: "Đặc biệt",
    minXp: 380,
    color: "#b1d9ed",
    symbol: "⚔",
    shape: "rays",
  },
  {
    id: "yin-yang",
    name: "Âm dương",
    group: "Đặc biệt",
    minXp: 640,
    color: "#e5e9f1",
    symbol: "☯",
    shape: "runes",
  },
  {
    id: "formation",
    name: "Thiên cơ trận",
    group: "Đặc biệt",
    minXp: 980,
    color: "#bda0ff",
    symbol: "阵",
    shape: "runes",
  },
  {
    id: "stars",
    name: "Tinh hà",
    group: "Đặc biệt",
    minXp: 1420,
    color: "#b2bdf6",
    symbol: "✶",
    shape: "runes",
  },
];

export function unlockedFrame(id: string | undefined, xp: number) {
  const frame = avatarFrames.find((item) => item.id === id);
  return frame && xp >= frame.minXp ? frame : avatarFrames[0];
}
