begin;
alter table public.app_users add column if not exists avatar_frame_grants text[] not null default '{}';
-- Administration owns every cosmetic and starts at the highest cultivation phase.
update public.app_users set cultivation_xp = greatest(cultivation_xp, 11900) where role = 'admin';
create table if not exists public.admin_community_audit (
  id bigint generated by default as identity primary key,
  actor_email text not null,
  action text not null check (action in ('profile_support','world_moderation')),
  target_id bigint not null,
  before_data jsonb not null,
  after_data jsonb not null,
  reason text not null check (char_length(reason) between 3 and 300),
  created_at timestamptz not null default now()
);
alter table public.admin_community_audit enable row level security;
revoke all on public.admin_community_audit from anon, authenticated;
grant all on public.admin_community_audit to service_role;
grant usage, select on sequence public.admin_community_audit_id_seq to service_role;
create index if not exists admin_community_audit_recent_idx on public.admin_community_audit(id desc);

create or replace function public.admin_support_profile(p_actor text, p_id bigint, p_expected jsonb, p_next jsonb, p_reason text)
returns void language plpgsql security definer set search_path = public as $$
declare old_row public.app_users; snapshot jsonb;
begin
  if not exists (select 1 from public.app_users where email = p_actor and role = 'admin' and status = 'Đang hoạt động') then
    raise exception 'Admin required' using errcode = '42501';
  end if;
  select * into old_row from public.app_users where id = p_id for update;
  if not found then raise exception 'Profile missing' using errcode = 'P0002'; end if;
  snapshot := jsonb_build_object('name',old_row.name,'bio',coalesce(old_row.bio,''),'avatarId',old_row.avatar_id,
    'avatarFrameId',coalesce(old_row.avatar_frame_id,'none'),'cultivationXp',old_row.cultivation_xp,'frameGrants',old_row.avatar_frame_grants);
  if snapshot <> p_expected then raise exception 'Profile changed; reload' using errcode = '40001'; end if;
  update public.app_users set name = p_next->>'name', bio = p_next->>'bio', avatar_id = p_next->>'avatarId',
    avatar_frame_id = p_next->>'avatarFrameId', cultivation_xp = (p_next->>'cultivationXp')::integer,
    avatar_frame_grants = array(select jsonb_array_elements_text(p_next->'frameGrants')) where id = p_id;
  insert into public.admin_community_audit(actor_email,action,target_id,before_data,after_data,reason)
    values(p_actor,'profile_support',p_id,snapshot,p_next,trim(p_reason));
end $$;
revoke all on function public.admin_support_profile(text,bigint,jsonb,jsonb,text) from public, anon, authenticated;
grant execute on function public.admin_support_profile(text,bigint,jsonb,jsonb,text) to service_role;

create or replace function public.admin_moderate_world(p_actor text, p_id bigint, p_status text, p_reason text)
returns void language plpgsql security definer set search_path = public as $$
declare prior text;
begin
  if not exists (select 1 from public.app_users where email = p_actor and role = 'admin' and status = 'Đang hoạt động') then
    raise exception 'Admin required' using errcode = '42501';
  end if;
  if p_status not in ('visible','hidden') then raise exception 'Invalid status' using errcode = '22023'; end if;
  select status into prior from public.world_messages where id = p_id for update;
  if not found then raise exception 'Message missing' using errcode = 'P0002'; end if;
  update public.world_messages set status = p_status where id = p_id;
  insert into public.admin_community_audit(actor_email,action,target_id,before_data,after_data,reason)
    values(p_actor,'world_moderation',p_id,jsonb_build_object('status',prior),jsonb_build_object('status',p_status),trim(p_reason));
end $$;
revoke all on function public.admin_moderate_world(text,bigint,text,text) from public, anon, authenticated;
grant execute on function public.admin_moderate_world(text,bigint,text,text) to service_role;
commit;
