-- Migration for Notifications, Movie Follows, and Multi-track Media

-- 1. Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
    type text NOT NULL, -- 'new_episode', 'friend_request', 'message', 'comment_reply', 'system'
    content text NOT NULL,
    link text,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role full access on notifications" ON public.notifications
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Index for fast lookup by user
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);


-- 2. Movie Follows Table
CREATE TABLE IF NOT EXISTS public.movie_follows (
    user_id bigint NOT NULL REFERENCES public.app_users(id) ON DELETE CASCADE,
    movie_id bigint NOT NULL REFERENCES public.movies(id) ON DELETE CASCADE,
    notify_new_episode boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, movie_id)
);

-- RLS
ALTER TABLE public.movie_follows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role full access on movie_follows" ON public.movie_follows
    FOR ALL TO service_role USING (true) WITH CHECK (true);


-- 3. Update Movies Table for Multi-track Support
-- Add JSONB columns for subtitles and audios arrays if they don't exist
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'movies' AND column_name = 'subtitles_data') THEN
        ALTER TABLE public.movies ADD COLUMN subtitles_data jsonb DEFAULT '[]'::jsonb;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'movies' AND column_name = 'audios_data') THEN
        ALTER TABLE public.movies ADD COLUMN audios_data jsonb DEFAULT '[]'::jsonb;
    END IF;
END $$;

-- Migrate existing single track data to the new JSONB arrays
UPDATE public.movies
SET subtitles_data = jsonb_build_array(jsonb_build_object('label', 'Vietnamese', 'lang', 'vi', 'url', subtitle_key))
WHERE subtitle_key IS NOT NULL AND subtitles_data = '[]'::jsonb;

UPDATE public.movies
SET audios_data = jsonb_build_array(jsonb_build_object('label', 'Bản lồng tiếng', 'url', audio_key))
WHERE audio_key IS NOT NULL AND audios_data = '[]'::jsonb;
